//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class concepts_status_logs
    {
        public int concept_status_log_id { get; set; }
        public int concept_id { get; set; }
        public int concept_status_id { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<int> user_id_created { get; set; }
        public Nullable<int> reason_reject_id { get; set; }
        public Nullable<int> qualification { get; set; }
    
        public virtual concepts_status concepts_status { get; set; }
        public virtual reason_rejects reason_rejects { get; set; }
        public virtual concepts concepts { get; set; }
    }
}
