//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class investigators
    {
        public int investigator_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string first_name { get; set; }
        public string second_name { get; set; }
        public string last_name { get; set; }
        public string second_last_name { get; set; }
        public Nullable<int> gender_id { get; set; }
        public string mobile_phone { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
    
        public virtual genders genders { get; set; }
        public virtual users users { get; set; }
    }
}
