//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class snies
    {
        public int snie_id { get; set; }
        public Nullable<int> educational_institution_id { get; set; }
        public Nullable<int> knowledge_area_id { get; set; }
        public Nullable<int> program_id { get; set; }
        public Nullable<int> academic_level_id { get; set; }
        public Nullable<int> education_level_id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
        public Nullable<int> user_id_created { get; set; }
        public Nullable<int> user_id_modified { get; set; }
    
        public virtual education_levels education_levels { get; set; }
        public virtual educational_institutions educational_institutions { get; set; }
        public virtual knowledge_areas knowledge_areas { get; set; }
        public virtual programs programs { get; set; }
    }
}
